// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc9Qym6MG8hyBznepxEYXaYY8bzu1kwg8',
    appId: '1:336580157107:web:603fe9d2bf9e558cfddac6',
    messagingSenderId: '336580157107',
    projectId: 'code-genie-a5d2c',
    authDomain: 'code-genie-a5d2c.firebaseapp.com',
    storageBucket: 'code-genie-a5d2c.firebasestorage.app',
    measurementId: 'G-VBW3X926Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIOIHTPIbiSPcGgOBxGz-R1TMDVBFrv2Q',
    appId: '1:336580157107:android:de5cfedcce83f6eefddac6',
    messagingSenderId: '336580157107',
    projectId: 'code-genie-a5d2c',
    storageBucket: 'code-genie-a5d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7GtpW7GwAp34LduhXgedfXIl_EUAWOO0',
    appId: '1:336580157107:ios:2815bea81dd8c013fddac6',
    messagingSenderId: '336580157107',
    projectId: 'code-genie-a5d2c',
    storageBucket: 'code-genie-a5d2c.firebasestorage.app',
    iosBundleId: 'com.chintan.codegenie',
  );
}
